import type { Event, Organisation, TeamMember } from '../types';

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Tolu Adebayo',
    title: 'Head of Ecosystem & Partnerships',
    unit: 'Strategic Alliances',
    role: 'Lead',
    phone: '+234 803 451 9820',
    email: 'tolu@loops.ng',
    bio: 'Leads sovereign compute partnerships, regional innovation corridors, and public-private AI initiatives.',
  },
  {
    id: 'tm-2',
    name: 'Chidi Okafor',
    title: 'Senior Partner Ops Manager',
    unit: 'Ecosystem Growth',
    role: 'Admin',
    phone: '+234 812 874 3319',
    email: 'chidi@loops.ng',
    bio: 'Oversees partner onboarding, pipeline governance, and technical co-sponsorship tracking.',
  },
  {
    id: 'tm-3',
    name: 'Amina Bello',
    title: 'Lead Curator & Ingest Lead',
    unit: 'Curatorial & Editorial',
    role: 'Editor',
    phone: '+234 809 112 7643',
    email: 'amina@loops.ng',
    bio: 'Curates grassroots Nigerian AI and tech events, research symposiums, and community workshops.',
  },
  {
    id: 'tm-4',
    name: 'Damilola Yusuf',
    title: 'Developer Relations & Tech Guilds',
    unit: 'Community Outreach',
    role: 'Editor',
    phone: '+234 705 993 4108',
    email: 'damilola@loops.ng',
    bio: 'Connects academic research circles, hacker collectives, and open-source West African NLP projects.',
  },
  {
    id: 'tm-5',
    name: 'Ngozi Eze',
    title: 'Ecosystem Analyst',
    unit: 'Intelligence & Reporting',
    role: 'Viewer',
    phone: '+234 818 204 5591',
    email: 'ngozi@loops.ng',
    bio: 'Tracks cross-sector conversion metrics, quarterly partner KPI scoring, and community health data.',
  },
];

export const mockOrganisations: Organisation[] = [
  {
    id: 'org-1',
    name: 'Blockchain & AI Ecosystem Association',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Champion',
    owner: 'Tolu Adebayo',
    nextAction: 'Finalise Landmark Event Centre stage specs and international speaker logistics',
    nextActionAt: '2026-09-25T10:00:00Z',
    status: 'active',
    website: 'https://nigeriablockchainaiweek.ng',
    description: 'National coalition organising Nigeria Blockchain & AI Week 2026 under the Agenda 2036 framework with 100+ global speakers.',
    contacts: [
      { id: 'c-1', name: 'Dr. Chuka Monye', title: 'Convener & Chairman', email: 'chuka@nigeriablockchainaiweek.ng', phone: '+234 802 334 1109', isPrimary: true },
      { id: 'c-2', name: 'Zainab Bello', title: 'Director of Policy Alliances', email: 'zainab@nigeriablockchainaiweek.ng', phone: '+234 814 990 2231' },
    ],
    interactions: [
      { id: 'int-1', date: '2026-09-20T14:30:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Aligned on ministerial keynote panel and stablecoin regulatory sandboxing session.', loggedBy: 'Tolu Adebayo' },
      { id: 'int-2', date: '2026-09-15T10:00:00Z', channel: 'Email', direction: 'Inbound', summary: 'Received final conference programme and hackathon problem statements.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 98, visits: 8450, contributions: 12, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-2',
    name: 'AI Forum Nigeria & National AI Alliance',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Champion',
    owner: 'Tolu Adebayo',
    nextAction: 'Confirm Lagos Oriental Hotel VIP delegate briefing schedule',
    nextActionAt: '2026-09-28T14:00:00Z',
    status: 'active',
    website: 'https://aiforum.ng',
    description: 'The dedicated apex forum for Nigerian AI policy leaders, academic researchers, and institutional technology executives.',
    contacts: [
      { id: 'c-3', name: 'Prof. Folashade Ogunsola', title: 'Steering Committee Chair', email: 'chair@aiforum.ng', phone: '+234 803 771 9044', isPrimary: true },
    ],
    interactions: [
      { id: 'int-3', date: '2026-09-18T16:00:00Z', channel: 'Call', direction: 'Outbound', summary: 'Confirmed keynote topics on national compute sovereign clusters and LLM data dignity.', loggedBy: 'Tolu Adebayo' },
    ],
    kpis: { periodScore: 95, visits: 5200, contributions: 9, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-3',
    name: 'GritinAI',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Partnered',
    owner: 'Damilola Yusuf',
    nextAction: 'Finalise Victor Uwaifo Creative Hub AV setup and livestream testing in Benin',
    nextActionAt: '2026-09-24T11:00:00Z',
    status: 'active',
    website: 'https://gritinai.com',
    description: 'Pioneering practical applied AI adoption, regional builder chapters, and real-world ML deployment across South-South Nigeria.',
    contacts: [
      { id: 'c-4', name: 'Osasere Osagie', title: 'Founder & AI Lead', email: 'osas@gritinai.com', phone: '+234 809 555 4321', isPrimary: true },
    ],
    interactions: [
      { id: 'int-4', date: '2026-09-19T09:00:00Z', channel: 'Email', direction: 'Outbound', summary: 'Sent co-branding promotional collateral for GritinAI Connect Benin City.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 91, visits: 3890, contributions: 6, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-4',
    name: 'IEEE Nigeria Section & UNILAG',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Partnered',
    owner: 'Damilola Yusuf',
    nextAction: 'Review peer-reviewed AI paper submissions and IEEE Xplore indexing metadata',
    nextActionAt: '2026-09-26T10:00:00Z',
    status: 'active',
    website: 'https://ieeenigercon.org',
    description: 'Technical academic community hosting NIGERCON 2026 with an intensive Artificial Intelligence and Big Data research track at UNILAG.',
    contacts: [
      { id: 'c-5', name: 'Engr. Dr. Abdullahi Musa', title: 'Technical Program Chair', email: 'musa.a@ieee.org', phone: '+234 802 118 7632', isPrimary: true },
    ],
    interactions: [
      { id: 'int-5', date: '2026-09-14T11:30:00Z', channel: 'In-Person', direction: 'Inbound', summary: 'Met with UNILAG engineering dean regarding student workshop scholarships.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 89, visits: 4100, contributions: 7, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-5',
    name: 'Fintech Association of Nigeria (FintechNGR)',
    sector: 'Fintech',
    tier: 'Tier 1',
    stage: 'Champion',
    owner: 'Chidi Okafor',
    nextAction: 'Coordinate live event coverage across Lagos, Abuja, and Port Harcourt nodes',
    nextActionAt: '2026-09-22T08:00:00Z',
    status: 'active',
    website: 'https://fintechng.org',
    description: 'Nigeria’s premier self-regulatory fintech umbrella body organising the annual Nigeria Fintech Week.',
    contacts: [
      { id: 'c-6', name: 'Dr. Babatunde Obrimah', title: 'Chief Operating Officer', email: 'bobrimah@fintechng.org', phone: '+234 803 124 5567', isPrimary: true },
    ],
    interactions: [
      { id: 'int-6', date: '2026-09-21T15:00:00Z', channel: 'Call', direction: 'Outbound', summary: 'Final check-in on event opening ceremonies and AI in fraud detection panel.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 96, visits: 9800, contributions: 14, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-6',
    name: 'AI & Automation Guild Nigeria',
    sector: 'Artificial Intelligence',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Amina Bello',
    nextAction: 'Distribute participant terminal codes for Zone Tech Park masterclass',
    nextActionAt: '2026-09-23T12:00:00Z',
    status: 'active',
    website: 'https://aiautomation.ng',
    description: 'Community of enterprise automation engineers, RPA practitioners, and autonomous agent swarms architects.',
    contacts: [
      { id: 'c-7', name: 'Kolawole Sanusi', title: 'Guild Coordinator', email: 'kola@aiautomation.ng', phone: '+234 812 770 1923', isPrimary: true },
    ],
    interactions: [
      { id: 'int-7', date: '2026-09-20T17:00:00Z', channel: 'Email', direction: 'Inbound', summary: 'Received curriculum slides on LangGraph and workflow agent benchmarks.', loggedBy: 'Amina Bello' },
    ],
    kpis: { periodScore: 78, visits: 1650, contributions: 3, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-7',
    name: 'SME Africa Network',
    sector: 'Fintech',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Chidi Okafor',
    nextAction: 'Confirm SME digital tool showcase sponsors at Civic Centre',
    nextActionAt: '2026-09-27T10:00:00Z',
    status: 'active',
    website: 'https://smeafricasummit.org',
    description: 'Supporting 50,000+ Nigerian micro-enterprises with AI accounting, supply chain logistics, and payment integration.',
    contacts: [
      { id: 'c-8', name: 'Grace Adeleke', title: 'Program Lead', email: 'grace@smeafricasummit.org', phone: '+234 805 441 2289', isPrimary: true },
    ],
    interactions: [
      { id: 'int-8', date: '2026-09-16T11:00:00Z', channel: 'WhatsApp', direction: 'Outbound', summary: 'Shared exhibition booth allocations for early-stage proptech and edtech sponsors.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 75, visits: 2100, contributions: 4, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-8',
    name: 'National Centre for AI & Robotics (NCAIR)',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Champion',
    owner: 'Tolu Adebayo',
    nextAction: 'Review 3MTT and national AI fellowship graduation project papers in Abuja',
    nextActionAt: '2026-09-29T09:00:00Z',
    status: 'active',
    website: 'https://ncair.nitda.gov.ng',
    description: 'Federal digital innovation centre driving national AI research, sovereign computing clusters, and deep tech incubation.',
    contacts: [
      { id: 'c-9', name: 'Dr. Bunmi Ajila', title: 'Director of Research', email: 'bunmi.ajila@ncair.gov.ng', phone: '+234 803 220 8911', isPrimary: true },
    ],
    interactions: [
      { id: 'int-9', date: '2026-09-17T14:00:00Z', channel: 'Call', direction: 'Outbound', summary: 'Agreed on evaluation metrics for national fellow NLP model prototypes.', loggedBy: 'Tolu Adebayo' },
    ],
    kpis: { periodScore: 94, visits: 6300, contributions: 10, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-9',
    name: 'CWG Plc & TeXcellence Council',
    sector: 'Fintech',
    tier: 'Tier 1',
    stage: 'Partnered',
    owner: 'Chidi Okafor',
    nextAction: 'Finalise banking CTO panel at Balmoral Convention Centre',
    nextActionAt: '2026-10-02T11:00:00Z',
    status: 'active',
    website: 'https://texcellenceconference.com',
    description: 'Flagship enterprise technology conveners highlighting cloud migration, AI in banking infrastructure, and cybersecurity.',
    contacts: [
      { id: 'c-10', name: 'Adewale Adeyipo', title: 'Group CEO', email: 'adewale@cwg-plc.com', phone: '+234 816 772 4430', isPrimary: true },
    ],
    interactions: [
      { id: 'int-10', date: '2026-09-15T15:00:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Discussed sovereign enterprise AI infrastructure adoption in Nigerian tier-1 banks.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 88, visits: 4500, contributions: 5, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-10',
    name: 'Inspire Africa Initiative',
    sector: 'Creative Tech',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Amina Bello',
    nextAction: 'Confirm venture partner lineup for Eko Hotel Grand Ballroom',
    nextActionAt: '2026-10-04T10:00:00Z',
    status: 'active',
    website: 'https://inspireafricaconference.org',
    description: 'Curating premier continental gatherings uniting technology pioneers, venture capitalists, and innovators.',
    contacts: [
      { id: 'c-11', name: 'Ifeoma Okonkwo', title: 'Executive Producer', email: 'ifeoma@inspireafricaconference.org', phone: '+234 802 441 5590', isPrimary: true },
    ],
    interactions: [
      { id: 'int-11', date: '2026-09-12T16:00:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Completed site visit at Eko Hotel Grand Ballroom.', loggedBy: 'Amina Bello' },
    ],
    kpis: { periodScore: 82, visits: 3100, contributions: 4, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-11',
    name: 'Arewa Tech Community',
    sector: 'Artificial Intelligence',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Damilola Yusuf',
    nextAction: 'Finalise travel bursaries for Northern tech delegates traveling to Lagos',
    nextActionAt: '2026-10-08T09:00:00Z',
    status: 'active',
    website: 'https://arewatechfest.com',
    description: 'Grassroots Northern Nigeria developer community spearheading Hausa speech models and regional digital trade.',
    contacts: [
      { id: 'c-12', name: 'Mustapha Shehu', title: 'Community Convener', email: 'mustapha@arewatechfest.com', phone: '+234 803 881 7722', isPrimary: true },
    ],
    interactions: [
      { id: 'int-12', date: '2026-09-11T13:00:00Z', channel: 'Email', direction: 'Outbound', summary: 'Confirmed hackathon prizes for the Hausa dialect synthetic dataset track.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 80, visits: 2700, contributions: 4, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-12',
    name: 'Rivers Tech Network & Niger Delta PropTech Guild',
    sector: 'Creative Tech',
    tier: 'Tier 2',
    stage: 'Partnered',
    owner: 'Chidi Okafor',
    nextAction: 'Confirm Golden Tulip Port Harcourt audio-visual and proptech demo stands',
    nextActionAt: '2026-10-15T10:00:00Z',
    status: 'active',
    website: 'https://proptechph.ng',
    description: 'Port Harcourt hub advancing smart city telemetry, land registry digitisation, and AI property analytics across the South-South.',
    contacts: [
      { id: 'c-13', name: 'Tamuno Briggs', title: 'Port Harcourt Convener', email: 'tamuno@proptechph.ng', phone: '+234 810 449 1180', isPrimary: true },
    ],
    interactions: [
      { id: 'int-13', date: '2026-09-14T11:00:00Z', channel: 'Call', direction: 'Inbound', summary: 'Aligned on Port Harcourt real estate developer roundtables and GIS sensor demos.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 84, visits: 2950, contributions: 5, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-13',
    name: 'GAMMA Technology Group',
    sector: 'Artificial Intelligence',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Damilola Yusuf',
    nextAction: 'Publish official speaker agenda for The Zone Gbagada',
    nextActionAt: '2026-10-18T13:00:00Z',
    status: 'active',
    website: 'https://gammatechsummit.com',
    description: 'International tech collective driving high-scale distributed backend systems, ML engineering, and cloud platforms.',
    contacts: [
      { id: 'c-14', name: 'Femi Johnson', title: 'Lead Architect', email: 'femi@gammatechsummit.com', phone: '+234 805 119 4022', isPrimary: true },
    ],
    interactions: [
      { id: 'int-14', date: '2026-09-10T14:00:00Z', channel: 'Email', direction: 'Outbound', summary: 'Invited local open-source maintainers to host lightning talks.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 76, visits: 1800, contributions: 3, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-14',
    name: 'Edo Innovates & Benin Tech Community',
    sector: 'Artificial Intelligence',
    tier: 'Tier 2',
    stage: 'Partnered',
    owner: 'Amina Bello',
    nextAction: 'Confirm government innovation grant finalists for Benin Tech Fest 2.0',
    nextActionAt: '2026-10-20T11:00:00Z',
    status: 'active',
    website: 'https://benintechfest.ng',
    description: 'Edo State innovation agency fostering software incubation, robotics labs, and digital skills.',
    contacts: [
      { id: 'c-15', name: 'Precious Ikhide', title: 'Managing Director', email: 'precious@edoinnovates.ng', phone: '+234 802 884 1009', isPrimary: true },
    ],
    interactions: [
      { id: 'int-15', date: '2026-09-12T10:00:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Walked through the Sir Victor Uwaifo Soundstage stage configuration.', loggedBy: 'Amina Bello' },
    ],
    kpis: { periodScore: 87, visits: 3400, contributions: 6, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-15',
    name: 'IMT Advisory Council',
    sector: 'Fintech',
    tier: 'Tier 2',
    stage: 'Engaged',
    owner: 'Chidi Okafor',
    nextAction: 'Release Insurance Meets Tech actuarial AI whitepaper draft',
    nextActionAt: '2026-10-28T10:00:00Z',
    status: 'active',
    website: 'https://insurancemeetstech.com',
    description: 'Accelerating AI underwriting, IoT claims assessment, and digital insurance penetration across West Africa.',
    contacts: [
      { id: 'c-16', name: 'Odion Martins', title: 'Conference Director', email: 'odion@insurancemeetstech.com', phone: '+234 809 332 7711', isPrimary: true },
    ],
    interactions: [
      { id: 'int-16', date: '2026-09-08T15:00:00Z', channel: 'WhatsApp', direction: 'Inbound', summary: 'Confirmed keynotes from NAICOM and leading digital insurtechs.', loggedBy: 'Chidi Okafor' },
    ],
    kpis: { periodScore: 79, visits: 2200, contributions: 3, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-16',
    name: 'Automation Nigeria Builders Guild',
    sector: 'Artificial Intelligence',
    tier: 'Tier 2',
    stage: 'Contacted',
    owner: 'Amina Bello',
    nextAction: 'Review robotic process automation and AI workflow hackathon guidelines',
    nextActionAt: '2026-10-30T14:00:00Z',
    status: 'active',
    website: 'https://9jaautomationfest.ng',
    description: 'Promoting robotic process automation, industrial IoT controllers, and autonomous workflow swarms in Nigerian enterprises.',
    contacts: [
      { id: 'c-17', name: 'Kunle Bakare', title: 'Guild President', email: 'kunle@9jaautomationfest.ng', phone: '+234 803 912 3344', isPrimary: true },
    ],
    interactions: [
      { id: 'int-17', date: '2026-09-05T12:00:00Z', channel: 'Email', direction: 'Outbound', summary: 'Provided guidelines for multi-agent framework demos at Landmark Hall 2.', loggedBy: 'Amina Bello' },
    ],
    kpis: { periodScore: 72, visits: 1450, contributions: 2, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-17',
    name: 'Techfeast Community',
    sector: 'Creative Tech',
    tier: 'Tier 3',
    stage: 'Contacted',
    owner: 'Damilola Yusuf',
    nextAction: 'Finalise open-air pavilion layout at Muri Okunola Park',
    nextActionAt: '2026-11-02T10:00:00Z',
    status: 'active',
    website: 'https://techfeast.ng',
    description: 'High-energy developer and creator festival celebrating open-source, indie hackers, and creative engineering.',
    contacts: [
      { id: 'c-18', name: 'Bukola Lawal', title: 'Lead Organiser', email: 'bukola@techfeast.ng', phone: '+234 814 119 8832', isPrimary: true },
    ],
    interactions: [
      { id: 'int-18', date: '2026-09-09T16:00:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Reviewed park permits and acoustic equipment zoning.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 68, visits: 1950, contributions: 2, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-18',
    name: 'Global AI Consortium & Nigerian AI Academic Forum',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Champion',
    owner: 'Tolu Adebayo',
    nextAction: 'Coordinate 7 simultaneous track program chairs across Eko Convention Centre',
    nextActionAt: '2026-11-10T10:00:00Z',
    status: 'active',
    website: 'https://7aiconferences.ng',
    description: 'International academic and industrial consortium orchestrating the 7 simultaneous international AI conferences in Lagos.',
    contacts: [
      { id: 'c-19', name: 'Dr. Kelechi Nwosu', title: 'Steering Committee General Chair', email: 'k.nwosu@7aiconferences.ng', phone: '+234 802 334 1109', isPrimary: true },
    ],
    interactions: [
      { id: 'int-19', date: '2026-09-18T10:00:00Z', channel: 'Call', direction: 'Outbound', summary: 'Aligned on international paper reviewers and keynote video links.', loggedBy: 'Tolu Adebayo' },
    ],
    kpis: { periodScore: 97, visits: 7800, contributions: 11, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
  {
    id: 'org-19',
    name: 'Build Nigeria Initiative & Hardware Guild',
    sector: 'Artificial Intelligence',
    tier: 'Tier 1',
    stage: 'Partnered',
    owner: 'Damilola Yusuf',
    nextAction: 'Finalise high-voltage safety and demo bay allocations for hardware finalists at Zone Tech Park',
    nextActionAt: '2026-11-15T11:00:00Z',
    status: 'active',
    website: 'https://buildnigeria.ng',
    description: 'Empowering Nigeria’s physical hardware makers, embedded edge ML engineers, and robotics prototypers.',
    contacts: [
      { id: 'c-20', name: 'Engr. Yemi Williams', title: 'Guild Lead & Chief Judge', email: 'yemi@buildnigeria.ng', phone: '+234 802 441 5590', isPrimary: true },
    ],
    interactions: [
      { id: 'int-20', date: '2026-09-16T14:00:00Z', channel: 'In-Person', direction: 'Outbound', summary: 'Inspected sensor testing bays and robotics runway at Zone Tech Park.', loggedBy: 'Damilola Yusuf' },
    ],
    kpis: { periodScore: 92, visits: 4900, contributions: 8, lastScoredAt: '2026-09-01T00:00:00Z' },
  },
];

export const mockEvents: Event[] = [
  // =========================================================================
  // SEPTEMBER 2026
  // =========================================================================
  {
    id: 'ev-1',
    slug: 'nigeria-fintech-week-2026',
    title: 'Nigeria Fintech Week 2026',
    description: "Nigeria's flagship financial technology convening uniting regulators, payment rails architects, neobank founders, and AI fraud prevention specialists across multi-city nodes in Lagos, Abuja, and Port Harcourt.",
    startDate: '2026-09-22T09:00:00Z',
    endDate: '2026-09-23T17:30:00Z',
    city: 'Lagos',
    venue: 'Landmark Centre, Victoria Island, Lagos (with hybrid hubs in Abuja & Port Harcourt)',
    organiser: 'Fintech Association of Nigeria (FintechNGR)',
    organiserId: 'org-5',
    category: 'Conference',
    format: 'Hybrid',
    priceType: 'Free',
    registrationUrl: 'https://nigeriafintechweek.org',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-2',
    slug: 'ai-automation-masterclass-lagos-2026',
    title: 'AI & Automation Masterclass Lagos',
    description: 'Intensive practitioner masterclass focusing on hands-on enterprise automation workflows, autonomous LLM agents, robotic process automation (RPA), and localized prompt architectures for operational efficiency.',
    startDate: '2026-09-24T10:00:00Z',
    endDate: '2026-09-24T16:00:00Z',
    city: 'Lagos',
    venue: 'Zone Tech Park, Plot 9 Gbagada Industrial Scheme, Lagos',
    organiser: 'AI & Automation Guild Nigeria',
    organiserId: 'org-6',
    category: 'Workshop',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦15,000',
    registrationUrl: 'https://aiautomation.ng/masterclass',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-3',
    slug: 'gritinai-connect-benin-2026',
    title: 'GritinAI Connect: Practical AI Adoption',
    description: 'Major South-South AI convening in Benin City dedicated to practical, production-ready AI adoption. Features live technical case studies on deploying computer vision in local agro-processing, offline generative AI for education, and fostering regional AI talent pipelines.',
    startDate: '2026-09-26T09:30:00Z',
    endDate: '2026-09-26T17:00:00Z',
    city: 'Benin City',
    venue: 'Victor Uwaifo Creative Hub, Airport Road, Benin City, Edo State',
    organiser: 'GritinAI',
    organiserId: 'org-3',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://gritinai.com/connect-benin',
    featured: true,
    status: 'published',
  },

  // =========================================================================
  // OCTOBER 2026
  // =========================================================================
  {
    id: 'ev-4',
    slug: 'sme-africa-summit-lagos-2026',
    title: 'SME Africa Summit 2026',
    description: 'Equipping micro, small, and medium businesses across Nigeria with actionable AI tools, automated bookkeeping solutions, digital storefront algorithms, and modern credit access pipelines.',
    startDate: '2026-10-03T09:00:00Z',
    endDate: '2026-10-03T17:00:00Z',
    city: 'Lagos',
    venue: 'The Civic Centre, Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
    organiser: 'SME Africa Network',
    organiserId: 'org-7',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://smeafricasummit.org',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-5',
    slug: 'tech-fellowship-data-science-ai-abuja-2026',
    title: 'Tech Fellowship: Data Science & AI Showcase',
    description: 'National fellows and applied researchers present computational models trained on sovereign Nigerian datasets, spanning public health diagnostics, agricultural yield forecasting, and civic data intelligence.',
    startDate: '2026-10-10T10:00:00Z',
    endDate: '2026-10-10T16:30:00Z',
    city: 'Abuja',
    venue: 'National Centre for Artificial Intelligence and Robotics (NCAIR), Wuye District, Abuja',
    organiser: 'National Centre for AI & Robotics (NCAIR)',
    organiserId: 'org-8',
    category: 'Workshop',
    format: 'Hybrid',
    priceType: 'Free',
    registrationUrl: 'https://ncair.nitda.gov.ng/fellowship-showcase',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-6',
    slug: 'texcellence-conference-lagos-2026',
    title: 'TeXcellence Conference 2026',
    description: 'High-level technology leadership convention uniting enterprise banking CIOs, telecommunications leaders, cloud infrastructure executives, and sovereign AI researchers steering digital Africa.',
    startDate: '2026-10-13T09:00:00Z',
    endDate: '2026-10-13T17:00:00Z',
    city: 'Lagos',
    venue: 'Balmoral Convention Centre, Federal Palace Hotel, Victoria Island, Lagos',
    organiser: 'CWG Plc & TeXcellence Council',
    organiserId: 'org-9',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦25,000',
    registrationUrl: 'https://texcellenceconference.com',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-7',
    slug: 'inspire-africa-conference-lagos-2026',
    title: 'Inspire Africa Conference 2026',
    description: 'Inspiring the next generation of African builders, venture operators, and deep tech founders with keynotes on artificial intelligence, sovereign capital, and scalable digital infrastructure.',
    startDate: '2026-10-14T09:00:00Z',
    endDate: '2026-10-14T18:00:00Z',
    city: 'Lagos',
    venue: 'Grand Ballroom, Eko Hotel & Suites, Victoria Island, Lagos',
    organiser: 'Inspire Africa Initiative',
    organiserId: 'org-10',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦20,000',
    registrationUrl: 'https://inspireafricaconference.org',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-8',
    slug: 'arewa-tech-fest-lagos-2026',
    title: 'Arewa Tech Fest 2026',
    description: 'Connecting Northern Nigerian developers, entrepreneurs, and researchers with the broader coastal ecosystem. Showcases Hausa natural language processing, rural connectivity mesh, and tech talent bridges.',
    startDate: '2026-10-21T09:00:00Z',
    endDate: '2026-10-22T17:00:00Z',
    city: 'Lagos',
    venue: 'Zone Tech Park, Plot 9 Gbagada Industrial Scheme, Lagos',
    organiser: 'Arewa Tech Community',
    organiserId: 'org-11',
    category: 'Conference',
    format: 'Hybrid',
    priceType: 'Free',
    registrationUrl: 'https://arewatechfest.com',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-9',
    slug: 'tech-for-real-estate-port-harcourt-2026',
    title: 'Tech for Real Estate Summit: PropTech & Smart Cities',
    description: 'Curated for builders and tech leaders in Port Harcourt and the Niger Delta. Covers AI property valuation engines, drone land surveying, smart IoT estate energy monitoring, and title tokenisation on digital ledgers.',
    startDate: '2026-10-31T10:00:00Z',
    endDate: '2026-10-31T16:30:00Z',
    city: 'Port Harcourt',
    venue: 'Golden Tulip Hotel, 1C Evo Road, GRA Phase 2, Port Harcourt, Rivers State',
    organiser: 'Rivers Tech Network & Niger Delta PropTech Guild',
    organiserId: 'org-12',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦10,000',
    registrationUrl: 'https://proptechph.ng',
    featured: false,
    status: 'published',
  },

  // =========================================================================
  // NOVEMBER 2026
  // =========================================================================
  {
    id: 'ev-10',
    slug: 'gamma-tech-summit-lagos-2026',
    title: 'GAMMA Tech Summit 2026',
    description: 'Premier assembly of software engineers, cloud architects, machine learning developers, and product leads exploring next-generation scalable platforms and API-first architectures.',
    startDate: '2026-11-05T09:00:00Z',
    endDate: '2026-11-05T17:00:00Z',
    city: 'Lagos',
    venue: 'The Zone Centre, Plot 9 Gbagada Industrial Scheme, Lagos',
    organiser: 'GAMMA Technology Group',
    organiserId: 'org-13',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://gammatechsummit.com',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-11',
    slug: 'benin-tech-fest-2026',
    title: 'Benin Tech Fest 2.0',
    description: 'The second edition of Edo State’s premier tech festival celebrating indigenous software products, AI hackathons, hardware prototypes, and the expansion of the Midwestern innovation corridor.',
    startDate: '2026-11-05T09:30:00Z',
    endDate: '2026-11-05T18:00:00Z',
    city: 'Benin City',
    venue: 'Edo Innovates Hub / Sir Victor Uwaifo Soundstage, Benin City, Edo State',
    organiser: 'Edo Innovates & Benin Tech Community',
    organiserId: 'org-14',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://benintechfest.ng',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-12',
    slug: 'ieee-nigercon-unilag-2026',
    title: 'IEEE NIGERCON 2026 (Heavy AI & Data Track)',
    description: 'The premier IEEE Nigeria International Conference featuring peer-reviewed research papers, IEEE Xplore indexing, and a heavy dedicated track on Artificial Intelligence, Deep Learning, Signal Processing, and Big Data.',
    startDate: '2026-11-05T08:30:00Z',
    endDate: '2026-11-06T17:30:00Z',
    city: 'Lagos',
    venue: 'Main Auditorium & Faculty of Engineering, University of Lagos (UNILAG), Akoka, Lagos',
    organiser: 'IEEE Nigeria Section & UNILAG',
    organiserId: 'org-4',
    category: 'Conference',
    format: 'Hybrid',
    priceType: 'Paid',
    price: '₦15,000',
    registrationUrl: 'https://ieeenigercon.org',
    featured: true,
    status: 'published',
  },
  {
    id: 'ev-13',
    slug: 'nigeria-blockchain-and-ai-week-2026',
    title: 'Nigeria Blockchain & AI Week 2026',
    description: 'The biggest AI event left in 2026. Theme: Agenda 2036 - AI, Blockchain & Stablecoins. Features 100+ high-profile speakers, federal policymakers, institutional investors, and frontier AI researchers dissecting sovereign intelligence, decentralized compute networks, and next-decade economic frameworks.',
    startDate: '2026-11-06T09:00:00Z',
    endDate: '2026-11-07T18:00:00Z',
    city: 'Lagos',
    venue: 'Landmark Event Centre, Water Corporation Drive, Victoria Island, Lagos',
    organiser: 'Blockchain & AI Ecosystem Association',
    organiserId: 'org-1',
    category: 'Conference',
    format: 'Hybrid',
    priceType: 'Free',
    registrationUrl: 'https://nigeriablockchainaiweek.ng',
    featured: true,
    status: 'published',
  },
  {
    id: 'ev-14',
    slug: 'insurance-meets-tech-lagos-2026',
    title: 'Insurance Meets Tech 2026 (IMT 4.0)',
    description: 'Where traditional insurance underwriting converges with AI risk analytics, IoT telematics, algorithmic claim verification, and climate insurance models tailored for the West African economy.',
    startDate: '2026-11-20T09:00:00Z',
    endDate: '2026-11-20T17:00:00Z',
    city: 'Lagos',
    venue: 'The Civic Centre, Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
    organiser: 'IMT Advisory Council',
    organiserId: 'org-15',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦30,000',
    registrationUrl: 'https://insurancemeetstech.com',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-15',
    slug: '9ja-automation-fest-lagos-2026',
    title: '9ja Automation Fest 2026',
    description: 'Celebrating robotic process automation (RPA), multi-agent swarms, industrial robotics, and no-code business process pipelines driving unprecedented productivity gains across Nigerian commercial sectors.',
    startDate: '2026-11-21T10:00:00Z',
    endDate: '2026-11-21T17:00:00Z',
    city: 'Lagos',
    venue: 'Landmark Centre (Hall 2), Water Corporation Drive, Victoria Island, Lagos',
    organiser: 'Automation Nigeria Builders Guild',
    organiserId: 'org-16',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://9jaautomationfest.ng',
    featured: false,
    status: 'published',
  },
  {
    id: 'ev-16',
    slug: 'techfeast-lagos-2026',
    title: 'Techfeast 2026 Lagos',
    description: 'Energetic outdoor technology festival and developer banquet uniting software engineers, product designers, game builders, and AI enthusiasts for interactive showcases, live demos, and builder camaraderie.',
    startDate: '2026-11-28T10:00:00Z',
    endDate: '2026-11-28T18:00:00Z',
    city: 'Lagos',
    venue: 'Muri Okunola Park & Pavilions, Victoria Island, Lagos',
    organiser: 'Techfeast Community',
    organiserId: 'org-17',
    category: 'Meetup',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://techfeast.ng',
    featured: false,
    status: 'published',
  },

  // =========================================================================
  // DECEMBER 2026
  // =========================================================================
  {
    id: 'ev-17',
    slug: 'the-ai-forum-nigeria-2026',
    title: 'The AI Forum Nigeria 2026',
    description: 'Dedicated national AI conference convened at Lagos Oriental Hotel. Uniting AI research fellows, sovereign compute architects, corporate executives, and regulatory bodies mapping national artificial intelligence roadmaps.',
    startDate: '2026-12-08T09:00:00Z',
    endDate: '2026-12-08T17:30:00Z',
    city: 'Lagos',
    venue: 'Lagos Oriental Hotel, Grand Ballroom, 3 Lekki - Epe Expressway, Victoria Island, Lagos',
    organiser: 'AI Forum Nigeria & National AI Alliance',
    organiserId: 'org-2',
    category: 'Conference',
    format: 'In-Person',
    priceType: 'Paid',
    price: '₦20,000',
    registrationUrl: 'https://aiforum.ng',
    featured: true,
    status: 'published',
  },
  {
    id: 'ev-18',
    slug: '7-international-ai-conferences-lagos-2026',
    title: '7 International AI Conferences Lagos 2026',
    description: 'Unprecedented single-day simultaneous mega-summit co-locating 7 international AI tracks: Computer Vision & Robotics, Natural Language Processing for African Languages, AI in Clinical Healthcare, Generative Intelligence, AI Governance & Ethics, Edge & Embedded Machine Learning, and AI in Financial Systems.',
    startDate: '2026-12-13T08:30:00Z',
    endDate: '2026-12-13T19:00:00Z',
    city: 'Lagos',
    venue: 'Eko Convention Centre & Virtual Halls, Eko Hotel & Suites, Victoria Island, Lagos',
    organiser: 'Global AI Consortium & Nigerian AI Academic Forum',
    organiserId: 'org-18',
    category: 'Conference',
    format: 'Hybrid',
    priceType: 'Free',
    registrationUrl: 'https://7aiconferences.ng',
    featured: true,
    status: 'published',
  },
  {
    id: 'ev-19',
    slug: 'build-nigeria-final-hardware-ai-products-2026',
    title: 'Build Nigeria Final: Hardware & AI Products',
    description: 'The grand national finale and demo day where Nigeria’s top hardware engineers and physical AI makers unveil real embedded edge sensors, agricultural drone telemetry systems, robotic prototypes, and sovereign compute hardware to angel investors and industry leaders.',
    startDate: '2026-12-19T10:00:00Z',
    endDate: '2026-12-19T18:00:00Z',
    city: 'Lagos',
    venue: 'Zone Tech Park, Plot 9 Gbagada Industrial Scheme, Lagos',
    organiser: 'Build Nigeria Initiative & Hardware Guild',
    organiserId: 'org-19',
    category: 'Demo Day',
    format: 'In-Person',
    priceType: 'Free',
    registrationUrl: 'https://buildnigeria.ng/final',
    featured: true,
    status: 'published',
  },
];
